### ISSUE TITLE
Access to server

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [Keristero/onb-modlister#1]
Hey I have a fork already but it requires mods and being configured with the bot. I'd like to hop into your server with the mods present to improve visuals and UX. You have my email you can send the credentials and I can get in that way to try my edits.

**Comment by Keristero** [comment]
Sent details to the email you provided me.

Keen to see what changes you have in mind, I was thinking of adding lazy loading and pagination at some point.

**Comment by Keristero** [comment]
Oh, and feel free to remove the individual download button and rick roll link, they are using precious space.

**Comment by ninjaman255** [comment]
is there a way to have it to where it asks for a directory, we give it resources/mods and it just auto fills what you downloaded in the right spots?

**Comment by ninjaman255** [comment]
[https://imgur.com/MBUfzWo](url) also i ended up whipping these up from some images online with some resizing, touch ups, etc. they might be useful for the end user to differentiate navi, enemies, chips and navi customizer parts in the preview to make it prettier. my thoughts are these images for their respective mod, and for skins just do the preview image thats used and blow it up to 320x320

**Comment by Keristero** [comment]
> is there a way to have it to where it asks for a directory, we give it resources/mods and it just auto fills what you downloaded in the right spots?

I dont think we can do that from the browser

> [https://imgur.com/MBUfzWo](url) also i ended up whipping these up from some images online with some resizing, touch ups, etc. they might be useful for the end user to differentiate navi, enemies, chips and navi customizer parts in the preview to make it prettier. my thoughts are these images for their respective mod, and for skins just do the preview image thats used and blow it up to 320x320

I could see that working, originally with the site I was going with a BN 1 kinda theme for the modsite as it is quite nostalgic.
It could certainly be a lot better though, I was never quite happy with the arrangement up to especially.

**Comment by ninjaman255** [comment]
> > is there a way to have it to where it asks for a directory, we give it resources/mods and it just auto fills what you downloaded in the right spots?
> 
> I dont think we can do that from the browser
> 
>>
as for this probably a dumb question. (ive never attempted it so im not certain on the intricacies of making it) how difficult/time consuming would it be to make a super barebones (i think the term for it is "bootstrapper") bootstrapper application that would serve this function. basically click download on the website it gives a prompt it wants to open "ONB-mod-bootstrap.exe", select directory then the bootstrapper downloads and delegates where the mods are put after download based on type (either that being meta data fed in from the website or from the method you use to read the type of mod on the website itself)

**Comment by Keristero** [comment]
That is somewhat doable.
I forget the exact name but it is something like Application URL Protocol.
James is already building a bootstrapper, but we could add a simple feature to the mod site which attempts to open the bootstrapper and install selected mods.
When the bootstrapper is installed it can register a custom URL Protocol in the OS which will allow the browser to open a prompt asking the user to allow the website access to message it.

This would be a sort of reverse workflow to what I understood that James had in mind. But it could be a good way to transition people from the mod site in future!
